"""order idempotency key

Revision ID: 59c0ecda7375
Revises: 4badf5e47534
Create Date: 2026-09-06 17:05:37.980036
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '59c0ecda7375'
down_revision: Union[str, Sequence[str], None] = '4badf5e47534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=64), nullable=False))
    op.create_unique_constraint('uq_orders_restaurant_idempotency', 'orders', ['restaurant_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_restaurant_idempotency', 'orders', type_='unique')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
